### ISSUE TITLE
Console error

### ISSUE THREAD

**Issue by beltez** [games647/ScoreboardStats#61]
Plugin work correctly, but console say this:

http://i.imgur.com/uusX8Xh.jpg

Thanks.

**Comment by games647** [comment]
There is no error in this log. You can ignore the entry about the missing file "ebean.properties". This file is used to configure the database settings. I simplified the configuration in the file "sql.yml".  The other log are just about to tell you that the database is created.

>executing 1 of 1[...]
How is the database be created? (Column name, Column type, index, ...)

>Entities [...]
How many classes are registered to eBean. In order to perform a ORM. (java implementation classes that represents database tables)

>SubClassFactory
Manager to load the these classes properly and not fail on a reload.

>DataSourcePool
General Information about the database connection (Connection name, transaction type, min and max concurrent connections)

>Using [...]
Implementation in order to find all resources that are needed for the connection. In this case it's a custom implementation in order to fix a bug in eBean where the plugin would crash on non-latin languages.

BTW eBean is the database manager which is embedded in Bukkit.
