### ISSUE TITLE
SUGGESTION tags, colored scoreboard...

### ISSUE THREAD

**Issue by Someone-NEW** [games647/ScoreboardStats#70]
Did you know why ColoredTags not working about SkyWars? your plugin work great about SW so i have suggestion to make for TAB and under player heads names with Group and colored names this vwill be AWESOME you are great whil you make this plugin an maybe you sometime update it to 1.8.8
adn suggestion to add Titles per worlds and subitles.

To-do:
- Under Head names (group, colored names)
- TAB (with groups and colored names
- Add Titles (Per world titles setings an subtitles)
- All test with SkyWarsReloaded and compatible with other plugins i hope for now your plugin is the best. I use Spigot 1.8.8 when you dont suport spigot than nevermind i hope you can help me?
So whn you can will be all in one place and realy cool updated, later you can add variables and what you want. All configurable in configs MANY THANKS.

**Comment by games647** [comment]
ColoredTags doesn't work with SkyWars, because of missing features in the scoreboard API of the server implementation. ScoreboardStats works around this issue by sending raw packets to the client. 

The features you are requesting should be separated in a different project. In order to keep ScoreboardStats simple it should only feature the sidebar.
