### ISSUE TITLE
Server Lagg

### ISSUE THREAD

**Issue by ireeskenz** [games647/ScoreboardStats#89]
Hello, i'm runing in Spigot 1.9.2 and I got actually a server lagg when we are 10 on the server with ScoreboardStats. TPS are unstable and very low. Can i do something ?

**Comment by games647** [comment]
Could you send me a timings report?

**Comment by ireeskenz** [comment]
https://timings.spigotmc.org/?url=15616057

**Comment by games647** [comment]
and your config please.

**Comment by games647** [comment]
The report is too short. 

>Total: **0.802s (Ticks: 1)** - Sample Time: 0.626s  - Spigot Version: ccb6016-f92e01b (MC: 1.9.2)

**Comment by ireeskenz** [comment]
My config of Scoreboardstats : http://pastebin.com/paYynEyh but i don't think that lagg come from config because i tried to remove config (clear) but the same lagg appear. How can i do a report more detailed ?

**Comment by games647** [comment]
>The problem is "56.70% 201.93% 4.85 s 100.96 ms 1.0 0.1k Task: RefreshTask(interval 1)"

You cannot say that, because the report is only about one tick. Just keep the timings longer activated and then make a report.

**Comment by ireeskenz** [comment]
I opened my server 30 Minutes. Here is timings : https://timings.spigotmc.org/?url=15631541

**Comment by games647** [comment]
What you could do is increasing the update-delay while I investigate what's the problem is.

**Comment by games647** [comment]
I guess I found it. Could you make a new timings report without the money variable? Please do a full server restart for this.

**Comment by ireeskenz** [comment]
Yeah, thanks my TPS are better now ! https://timings.spigotmc.org/?url=15633327

**Comment by games647** [comment]
Indeed 
>   0.04%	   0.04%	  1.11 s	     0.02 ms	 1.0	      58.5k	    Task: RefreshTask(interval 1)

Then it's a plugin issue of IConomy. It executes SQL-Queries on the main thread which can hurt the performance really hard as you saw. The plugin makes a connection to the database server (or program) and waits for the response. In the meanwhile it cannot perform other operations. 

The plugin could cache the balance for online players in order to reduce the lag, because ScoreboardStats and very likely many other plugins often ask only for the balance of online players.
